<a href="https://colab.research.google.com/github/MeghanGH/google-colaboratory-practical-statistics-for-data-scientists/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy Arrays

In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# [start, stop), step
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.random.rand(3,2)

array([[0.55388426, 0.8102943 ],
       [0.46552681, 0.18587581],
       [0.44265873, 0.84754612]])

In [ ]:
np.random.randint(1,100,2)

array([28, 42])

In [ ]:
ranarr = np.random.randint(0,10,10)
ranarr

array([1, 2, 4, 4, 9, 5, 0, 2, 4, 6])

In [ ]:
ranarr.reshape(2,5)

array([[1, 2, 4, 4, 9],
       [5, 0, 2, 4, 6]])

In [ ]:
ranarr.argmax()

4

In [ ]:
ranarr[ranarr.argmax()]

9

In [ ]:
arr.dtype

dtype('int64')

## Indexing

In [43]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [46]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [49]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [54]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [55]:
arr_copy = slice_of_arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99])

In [57]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
# arr_2[row][column]
arr_2d[2][2]

9

In [61]:
# arr_2[row,column]
arr_2d[1,2]

6

In [63]:
# arr_2[:row2][row1:]

arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [65]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
bool_arr = arr < 10
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True, False])

In [68]:
arr[arr<10]

array([6, 7, 8, 9])

In [69]:
arr_range = np.arange(100).reshape(10,10)
arr_range

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [72]:
arr_range[1:2,3:4]

array([[13]])

Operations

In [73]:
arr_op = np.arange(0,11)
arr_op

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr_op + arr_op

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [75]:
arr_op - arr_op

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [76]:
arr_op * arr_op

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [78]:
np.sqrt(arr_op)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [79]:
np.max(arr)

99